return {
  {
    "nvim-treesitter/nvim-treesitter",
    event = { "VeryLazy" },
    branch = 'master',
    lazy = false,
    build = ":TSUpdate",
    opts = {
      highlight = { enable = true },
      indent = { enable = true },
      auto_install = true,
      ensure_installed = {
        "bash",
        "c",
        "crystal",
        "css",
        "csv",
        "dart",
        "diff",
        "elixer",
        "elm",
        "erlang",
        "git_config",
        "gitcommit",
        "gitignore",
        "go",
        "html",
        "javascript",
        "jq",
        "json",
        "json5",
        "latex",
        "lua",
        "make",
        "markdown",
        "markdown_inline",
        "mermaid",
        "perl",
        "php",
        "python",
        "query",
        "ruby",
        "regex",
        "sql",
        "ssh_config",
        "terraform",
        "tmux",
        "toml",
        "tsx",
        "typescript",
        "typespec",
        "vim",
        "xml",
        "yaml",
      },
    },
  },

}
